### ISSUE TITLE
Item highlight off

### ISSUE THREAD

**Issue by Axelgrey** [TropicMango/ItemExchangeMod#1]
The red highlight is off from the item. Possibly dependant on the resolution?
Using 1920x1080 Hud scale 1.0
![image](https://user-images.githubusercontent.com/49280543/57135639-63569f80-6daa-11e9-8ab8-5d0ffdec68cb.png)

**Comment by TropicMango** [comment]
Oh shoot forgot to test for that one, thanks~

**Comment by Axelgrey** [comment]
Don't worry about it any more. Started working fine after one of your
updates.

Had some other strange occurances in coop but could not replicate it so
far. Apart from only working for host to drop from any player, something
desynced once and trying to drop from player 1's end list started dropping
duplicates of itema player 2 has.
Another thing is that with a lot of items it's a little hard to use since
the buttons overlap. Maybe changing the red buttons to be very small on top
of items would fix that.

**Comment by TropicMango** [comment]
Yea my goal is to get the mod working for each individual player so that it's not a "Host only" mod. But once I get that working I'm planning to move the buttons to the top of the screen where the personal item bars are, cuz they don't suffer from clumping and just scale down

**Comment by Axelgrey** [comment]
Sounds great.
Also just to let you know it doesn't work with the currently available mod
managers but that seems rather like something to fix from the modloaders
side.

**Comment by TropicMango** [comment]
Yea my goal is to get the mod working for each individual player so that it's not a "Host only" mod. But once I get that working I'm planning to move the buttons to the top of the screen where the personal item bars are, cuz they don't suffer from clumping and just scale down
